/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#line 1 "tests.check"
#include <check.h>
#include <stdio.h>

#include "../s21_decimal.h"

START_TEST(less_two_pos) {
#line 9
  s21_decimal n = {{1, 0, 0, 0}};
  s21_decimal m = {{0, 1, 0, 0}};
  ck_assert_int_eq(s21_is_less(n, m), TRUE);
}
END_TEST

START_TEST(less_two_neg) {
#line 14
  s21_decimal n = {{0, 1, 0, 0b10000000000000000000000000000000}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less(n, m), TRUE);
}
END_TEST

START_TEST(less_pos_neg) {
#line 19
  s21_decimal n = {{0, 1, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less(m, n), TRUE);
}
END_TEST

START_TEST(less_zero) {
#line 24
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less(m, n), TRUE);
}
END_TEST

START_TEST(less_scale) {
#line 29
  s21_decimal n = {{0, 0, 1, 0b00000000000001110000000000000000}};
  s21_decimal m = {{0, 0, 1, 0b00000000000000110000000000000000}};
  ck_assert_int_eq(s21_is_less(n, m), TRUE);
}
END_TEST

START_TEST(less_core) {
#line 34
  s21_decimal n = {{0b00000000000000000000000000011100, 0, 0, 0}};
  s21_decimal m = {{0b00000000000000000000000011111111, 0, 0,
                    0b00000000000001110000000000000000}};
  ck_assert_int_eq(s21_is_less(m, n), TRUE);
}
END_TEST
START_TEST(less_false_zeros) {
#line 41
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{0, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less(n, m), FALSE);
}
END_TEST

START_TEST(less_false_pos) {
#line 46
  s21_decimal n = {{0, 0, 1, 0}};
  s21_decimal m = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_less(n, m), FALSE);
}
END_TEST

START_TEST(res_false_neg) {
#line 51
  s21_decimal n = {{0, 0, 1, 0b10000000000000000000000000000000}};
  s21_decimal m = {{0, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less(m, n), FALSE);
}
END_TEST

START_TEST(less_zero_scale) {
#line 56
  s21_decimal n = {{0, 0, 0, 0b10000000000011110000000000000000}};
  s21_decimal m = {{0, 0, 0, 0b00000000000000110000000000000000}};
  ck_assert_int_eq(s21_is_less(n, m), FALSE);
}
END_TEST

START_TEST(less_false_signs) {
#line 61
  s21_decimal n = {{0, 0, 1, 0}};
  s21_decimal m = {{1, 1, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less(n, m), FALSE);

  /////////////////////////////////////////////////////////////////////////////////////////
}
END_TEST

START_TEST(gr_false_two_pos) {
#line 75
  s21_decimal n = {{1, 0, 0, 0}};
  s21_decimal m = {{0, 1, 0, 0}};
  ck_assert_int_eq(s21_is_greater(n, m), FALSE);
}
END_TEST

START_TEST(gr_false_two_neg) {
#line 80
  s21_decimal n = {{0, 1, 0, 0b10000000000000000000000000000000}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater(n, m), FALSE);
}
END_TEST

START_TEST(gr_false_pos_neg) {
#line 85
  s21_decimal n = {{0, 1, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater(m, n), FALSE);
}
END_TEST

START_TEST(gr_false_scale) {
#line 90
  s21_decimal n = {{0, 0, 1, 0b00000000000001110000000000000000}};
  s21_decimal m = {{0, 0, 1, 0b00000000000000110000000000000000}};
  ck_assert_int_eq(s21_is_greater(n, m), FALSE);
}
END_TEST

START_TEST(gr_false_zeros) {
#line 95
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{0, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater(n, m), FALSE);
}
END_TEST
START_TEST(gr_pos) {
#line 102
  s21_decimal n = {{0, 0, 1, 0}};
  s21_decimal m = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_greater(n, m), TRUE);
}
END_TEST

START_TEST(gr_neg) {
#line 107
  s21_decimal n = {{0, 0, 1, 0b10000000000000000000000000000000}};
  s21_decimal m = {{0, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater(m, n), TRUE);
}
END_TEST

START_TEST(gr_signs) {
#line 112
  s21_decimal n = {{0, 0, 1, 0}};
  s21_decimal m = {{1, 1, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater(n, m), TRUE);
}
END_TEST

START_TEST(gr_scale) {
#line 117
  s21_decimal n = {{0, 0, 1, 0}};
  s21_decimal m = {{0, 0, 1, 0b00000000000000110000000000000000}};
  ck_assert_int_eq(s21_is_greater(n, m), TRUE);
}
END_TEST

START_TEST(gr_zero) {
#line 122
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater(n, m), TRUE);

  /////////////////////////////////////////////////////////////////////////////////////////
}
END_TEST

START_TEST(eq_zeros) {
#line 136
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_equal(n, m), TRUE);
}
END_TEST

START_TEST(eq_zeros_signs) {
#line 141
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{0, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_equal(n, m), TRUE);
}
END_TEST

START_TEST(eq_scale) {
#line 146
  s21_decimal n = {{0b00000000000000000000010010110000, 0, 0,
                    0b00000000000000100000000000000000}};
  s21_decimal m = {{0b00000000000000000000000000001100, 0, 0, 0}};
  ck_assert_int_eq(s21_is_equal(n, m), TRUE);
}
END_TEST
START_TEST(eq_false_signs) {
#line 153
  s21_decimal n = {{1, 0, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_equal(n, m), FALSE);
}
END_TEST

START_TEST(eq_false_scale) {
#line 158
  s21_decimal n = {{0b00000000000000000000010010110000, 0, 0,
                    0b00000000000000100000000000000000}};
  s21_decimal m = {{0b00000000000000000000010010110000, 0, 0, 0}};
  ck_assert_int_eq(s21_is_equal(n, m), FALSE);

  /////////////////////////////////////////////////////////////////////////////////////////
}
END_TEST

START_TEST(not_true_sign) {
#line 172
  s21_decimal n = {{1, 0, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_not_equal(n, m), TRUE);
}
END_TEST

START_TEST(not_true_scale) {
#line 177
  s21_decimal n = {{0b00000000000000000000010010110000, 0, 0,
                    0b00000000000000100000000000000000}};
  s21_decimal m = {{0b00000000000000000000010010110000, 0, 0, 0}};
  ck_assert_int_eq(s21_is_not_equal(n, m), TRUE);
}
END_TEST
START_TEST(not_zeros) {
#line 184
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_not_equal(n, m), FALSE);
}
END_TEST

START_TEST(not_zeros_signs) {
#line 189
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{0, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_not_equal(n, m), FALSE);
}
END_TEST

START_TEST(not_scale) {
#line 194
  s21_decimal n = {{0b00000000000000000000010010110000, 0, 0,
                    0b00000000000000100000000000000000}};
  s21_decimal m = {{0b00000000000000000000000000001100, 0, 0, 0}};
  ck_assert_int_eq(s21_is_not_equal(n, m), FALSE);

  /////////////////////////////////////////////////////////////////////////////////////////
}
END_TEST

START_TEST(eq_less_two_pos) {
#line 208
  s21_decimal n = {{1, 0, 0, 0}};
  s21_decimal m = {{0, 1, 0, 0}};
  ck_assert_int_eq(s21_is_less_or_equal(n, m), TRUE);
}
END_TEST

START_TEST(eq_less_two_neg) {
#line 213
  s21_decimal n = {{0, 1, 0, 0b10000000000000000000000000000000}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less_or_equal(n, m), TRUE);
}
END_TEST

START_TEST(eq_less_pos_neg) {
#line 218
  s21_decimal n = {{0, 1, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less_or_equal(m, n), TRUE);
}
END_TEST

START_TEST(eq_less_zero) {
#line 223
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less_or_equal(m, n), TRUE);
}
END_TEST

START_TEST(eq_less_scale) {
#line 228
  s21_decimal n = {{0, 0, 1, 0b00000000000001110000000000000000}};
  s21_decimal m = {{0, 0, 1, 0b00000000000000110000000000000000}};
  ck_assert_int_eq(s21_is_less_or_equal(n, m), TRUE);
}
END_TEST

START_TEST(eq_less_core) {
#line 233
  s21_decimal n = {{0b00000000000000000000000000011100, 0, 0, 0}};
  s21_decimal m = {{0b00000000000000000000000011111111, 0, 0,
                    0b00000000000001110000000000000000}};
  ck_assert_int_eq(s21_is_less_or_equal(m, n), TRUE);
}
END_TEST

START_TEST(eq_less_zeros) {
#line 238
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_less_or_equal(n, m), TRUE);
}
END_TEST

START_TEST(eq_less_zeros_signs) {
#line 243
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{0, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less_or_equal(n, m), TRUE);
}
END_TEST

START_TEST(eq_less_scale_1) {
#line 248
  s21_decimal n = {{0b00000000000000000000010010110000, 0, 0,
                    0b00000000000000100000000000000000}};
  s21_decimal m = {{0b00000000000000000000000000001100, 0, 0, 0}};
  ck_assert_int_eq(s21_is_less_or_equal(n, m), TRUE);
}
END_TEST
START_TEST(el_false_signs) {
#line 255
  s21_decimal n = {{1, 0, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less_or_equal(n, m), FALSE);
}
END_TEST

START_TEST(el_false_scale) {
#line 260
  s21_decimal m = {{0b00000000000000000000010010110000, 0, 0,
                    0b00000000000000100000000000000000}};
  s21_decimal n = {{0b00000000000000000000010010110000, 0, 0, 0}};
  ck_assert_int_eq(s21_is_less_or_equal(n, m), FALSE);
}
END_TEST

START_TEST(el_false_pos) {
#line 265
  s21_decimal n = {{0, 0, 1, 0}};
  s21_decimal m = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_less_or_equal(n, m), FALSE);
}
END_TEST

START_TEST(el_false_neg) {
#line 270
  s21_decimal n = {{0, 0, 1, 0b10000000000000000000000000000000}};
  s21_decimal m = {{0, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_less_or_equal(m, n), FALSE);

  /////////////////////////////////////////////////////////////////////////////////////////
}
END_TEST

START_TEST(eg_pos) {
#line 284
  s21_decimal n = {{0, 0, 1, 0}};
  s21_decimal m = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_greater_or_equal(n, m), TRUE);
}
END_TEST

START_TEST(eg_neg) {
#line 289
  s21_decimal n = {{0, 0, 1, 0b10000000000000000000000000000000}};
  s21_decimal m = {{0, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater_or_equal(m, n), TRUE);
}
END_TEST

START_TEST(eg_signs) {
#line 294
  s21_decimal n = {{0, 0, 1, 0}};
  s21_decimal m = {{1, 1, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater_or_equal(n, m), TRUE);
}
END_TEST

START_TEST(eg_zero) {
#line 299
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater_or_equal(n, m), TRUE);
}
END_TEST

START_TEST(eg_zeros) {
#line 304
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{0, 0, 0, 0}};
  ck_assert_int_eq(s21_is_greater_or_equal(n, m), TRUE);
}
END_TEST

START_TEST(eg_zeros_signs) {
#line 309
  s21_decimal n = {{0, 0, 0, 0}};
  s21_decimal m = {{0, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater_or_equal(n, m), TRUE);
}
END_TEST

START_TEST(eg_scale) {
#line 314
  s21_decimal n = {{0b00000000000000000000010010110000, 0, 0,
                    0b00000000000000100000000000000000}};
  s21_decimal m = {{0b00000000000000000000000000001100, 0, 0, 0}};
  ck_assert_int_eq(s21_is_greater_or_equal(n, m), TRUE);
}
END_TEST
START_TEST(eg_false_two_pos) {
#line 321
  s21_decimal n = {{1, 0, 0, 0}};
  s21_decimal m = {{0, 1, 0, 0}};
  ck_assert_int_eq(s21_is_greater_or_equal(n, m), FALSE);
}
END_TEST

START_TEST(eg_false_two_neg) {
#line 326
  s21_decimal n = {{0, 1, 0, 0b10000000000000000000000000000000}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater_or_equal(n, m), FALSE);
}
END_TEST

START_TEST(eg_false_pos_neg) {
#line 331
  s21_decimal n = {{0, 1, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};
  ck_assert_int_eq(s21_is_greater_or_equal(m, n), FALSE);
}
END_TEST

START_TEST(eg_false_scale) {
#line 336
  s21_decimal n = {{0, 0, 1, 0b00000000000001110000000000000000}};
  s21_decimal m = {{0, 0, 1, 0b00000000000000110000000000000000}};
  ck_assert_int_eq(s21_is_greater_or_equal(n, m), FALSE);
}
END_TEST

START_TEST(eg_false_scale1) {
#line 341
  s21_decimal n = {{0b00000000000000000000010010110000, 0, 0,
                    0b00000000000000100000000000000000}};
  s21_decimal m = {{0b00000000000000000000010010110000, 0, 0, 0}};
  ck_assert_int_eq(s21_is_greater_or_equal(n, m), FALSE);

  /////////////////////////////////////////////////////////////////////////////////////////
}
END_TEST

START_TEST(to_neg) {
#line 355
  s21_decimal n = {{1, 0, 0, 0}};
  s21_decimal n1 = {{0, 0, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b10000000000000000000000000000000}};

  ck_assert_int_eq(s21_negate(n, &n1), 0);
  ck_assert_int_eq(s21_is_equal(n1, m), TRUE);
}
END_TEST

START_TEST(to_pos) {
#line 363
  s21_decimal n = {{1, 0, 0, 0b10000000000100000000000000000000}};
  s21_decimal n1 = {{0, 0, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b00000000000100000000000000000000}};

  ck_assert_int_eq(s21_negate(n, &n1), 0);
  ck_assert_int_eq(s21_is_equal(n1, m), TRUE);
}
END_TEST
START_TEST(neg_scale) {
#line 373
  s21_decimal n = {{1, 0, 0, 0b10000000001000000000000000000000}};
  s21_decimal n1 = {{0, 0, 0, 0}};
  s21_decimal m = {{1, 0, 0, 0b00000000001000000000000000000000}};

  ck_assert_int_eq(s21_negate(n, &n1), 1);
  ck_assert_int_eq(s21_is_equal(n1, m), FALSE);
}
END_TEST

START_TEST(neg_null) {
#line 381
  s21_decimal n = {{1, 0, 0, 0b10000000001000000000000000000000}};
  s21_decimal n1;
  s21_decimal m = {{1, 0, 0, 0b00000000001000000000000000000000}};

  ck_assert_int_eq(s21_negate(n, &n1), 1);
  ck_assert_int_eq(s21_is_equal(n1, m), FALSE);

  /////////////////////////////////////////////////////////////////////////////////////////
}
END_TEST

START_TEST(tr_norm1) {
#line 398
  s21_decimal n = {{123456789, 0, 0, 0b00000000000001110000000000000000}};
  s21_decimal n1 = {{0, 0, 0, 0}};
  s21_decimal m = {{12, 0, 0, 0}};

  ck_assert_int_eq(s21_truncate(n, &n1), 0);
  ck_assert_int_eq(s21_is_equal(n1, m), TRUE);
}
END_TEST

START_TEST(tr_norm2) {
#line 406
  s21_decimal n = {{0b11110010011010010010100100011101,
                    0b00001101101000100010110101011000, 0,
                    0b00000000000100000000000000000000}};
  s21_decimal n1 = {{0, 0, 0, 0}};
  s21_decimal m = {{98, 0, 0, 0}};

  ck_assert_int_eq(s21_truncate(n, &n1), 0);
  ck_assert_int_eq(s21_is_equal(n1, m), TRUE);
}
END_TEST
START_TEST(er_scale) {
#line 416
  s21_decimal n = {{0b11110010011010010010100100011101,
                    0b00001101101000100010110101011000, 0,
                    0b00000000001100000000000000000000}};
  s21_decimal n1 = {{0, 0, 0, 0}};
  s21_decimal m = {{98, 0, 0, 0}};

  ck_assert_int_eq(s21_truncate(n, &n1), 1);
  ck_assert_int_eq(s21_is_equal(n1, m), FALSE);
}
END_TEST

START_TEST(er_null) {
#line 424
  s21_decimal n = {{0b11110010011010010010100100011101,
                    0b00001101101000100010110101011000, 0,
                    0b00000000001100000000000000000000}};
  s21_decimal n1;
  s21_decimal m = {{98, 0, 0, 0}};

  ck_assert_int_eq(s21_truncate(n, &n1), 1);
  ck_assert_int_eq(s21_is_equal(n1, m), FALSE);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("less");
  TCase *tc1_1 = tcase_create("less_true");
  TCase *tc1_2 = tcase_create("less_false");
  Suite *s2 = suite_create("greater");
  TCase *tc2_1 = tcase_create("gr_false");
  TCase *tc2_2 = tcase_create("gr_true");
  Suite *s3 = suite_create("equal");
  TCase *tc3_1 = tcase_create("eq_right");
  TCase *tc3_2 = tcase_create("eq_false");
  Suite *s4 = suite_create("not_eq");
  TCase *tc4_1 = tcase_create("not_true");
  TCase *tc4_2 = tcase_create("not_false");
  Suite *s5 = suite_create("eq_less");
  TCase *tc5_1 = tcase_create("el_true");
  TCase *tc5_2 = tcase_create("el_false");
  Suite *s6 = suite_create("eq_gr");
  TCase *tc6_1 = tcase_create("eg_true");
  TCase *tc6_2 = tcase_create("eg_false");
  Suite *s7 = suite_create("negate");
  TCase *tc7_1 = tcase_create("neg_norm");
  TCase *tc7_2 = tcase_create("neg_err");
  Suite *s8 = suite_create("truncate");
  TCase *tc8_1 = tcase_create("tr_norm");
  TCase *tc8_2 = tcase_create("tr_er");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, less_two_pos);
  tcase_add_test(tc1_1, less_two_neg);
  tcase_add_test(tc1_1, less_pos_neg);
  tcase_add_test(tc1_1, less_zero);
  tcase_add_test(tc1_1, less_scale);
  tcase_add_test(tc1_1, less_core);
  suite_add_tcase(s1, tc1_2);
  tcase_add_test(tc1_2, less_false_zeros);
  tcase_add_test(tc1_2, less_false_pos);
  tcase_add_test(tc1_2, res_false_neg);
  tcase_add_test(tc1_2, less_zero_scale);
  tcase_add_test(tc1_2, less_false_signs);
  suite_add_tcase(s2, tc2_1);
  tcase_add_test(tc2_1, gr_false_two_pos);
  tcase_add_test(tc2_1, gr_false_two_neg);
  tcase_add_test(tc2_1, gr_false_pos_neg);
  tcase_add_test(tc2_1, gr_false_scale);
  tcase_add_test(tc2_1, gr_false_zeros);
  suite_add_tcase(s2, tc2_2);
  tcase_add_test(tc2_2, gr_pos);
  tcase_add_test(tc2_2, gr_neg);
  tcase_add_test(tc2_2, gr_signs);
  tcase_add_test(tc2_2, gr_scale);
  tcase_add_test(tc2_2, gr_zero);
  suite_add_tcase(s3, tc3_1);
  tcase_add_test(tc3_1, eq_zeros);
  tcase_add_test(tc3_1, eq_zeros_signs);
  tcase_add_test(tc3_1, eq_scale);
  suite_add_tcase(s3, tc3_2);
  tcase_add_test(tc3_2, eq_false_signs);
  tcase_add_test(tc3_2, eq_false_scale);
  suite_add_tcase(s4, tc4_1);
  tcase_add_test(tc4_1, not_true_sign);
  tcase_add_test(tc4_1, not_true_scale);
  suite_add_tcase(s4, tc4_2);
  tcase_add_test(tc4_2, not_zeros);
  tcase_add_test(tc4_2, not_zeros_signs);
  tcase_add_test(tc4_2, not_scale);
  suite_add_tcase(s5, tc5_1);
  tcase_add_test(tc5_1, eq_less_two_pos);
  tcase_add_test(tc5_1, eq_less_two_neg);
  tcase_add_test(tc5_1, eq_less_pos_neg);
  tcase_add_test(tc5_1, eq_less_zero);
  tcase_add_test(tc5_1, eq_less_scale);
  tcase_add_test(tc5_1, eq_less_core);
  tcase_add_test(tc5_1, eq_less_zeros);
  tcase_add_test(tc5_1, eq_less_zeros_signs);
  tcase_add_test(tc5_1, eq_less_scale_1);
  suite_add_tcase(s5, tc5_2);
  tcase_add_test(tc5_2, el_false_signs);
  tcase_add_test(tc5_2, el_false_scale);
  tcase_add_test(tc5_2, el_false_pos);
  tcase_add_test(tc5_2, el_false_neg);
  suite_add_tcase(s6, tc6_1);
  tcase_add_test(tc6_1, eg_pos);
  tcase_add_test(tc6_1, eg_neg);
  tcase_add_test(tc6_1, eg_signs);
  tcase_add_test(tc6_1, eg_zero);
  tcase_add_test(tc6_1, eg_zeros);
  tcase_add_test(tc6_1, eg_zeros_signs);
  tcase_add_test(tc6_1, eg_scale);
  suite_add_tcase(s6, tc6_2);
  tcase_add_test(tc6_2, eg_false_two_pos);
  tcase_add_test(tc6_2, eg_false_two_neg);
  tcase_add_test(tc6_2, eg_false_pos_neg);
  tcase_add_test(tc6_2, eg_false_scale);
  tcase_add_test(tc6_2, eg_false_scale1);
  suite_add_tcase(s7, tc7_1);
  tcase_add_test(tc7_1, to_neg);
  tcase_add_test(tc7_1, to_pos);
  suite_add_tcase(s7, tc7_2);
  tcase_add_test(tc7_2, neg_scale);
  tcase_add_test(tc7_2, neg_null);
  suite_add_tcase(s8, tc8_1);
  tcase_add_test(tc8_1, tr_norm1);
  tcase_add_test(tc8_1, tr_norm2);
  suite_add_tcase(s8, tc8_2);
  tcase_add_test(tc8_2, er_scale);
  tcase_add_test(tc8_2, er_null);

  srunner_add_suite(sr, s2);
  srunner_add_suite(sr, s3);
  srunner_add_suite(sr, s4);
  srunner_add_suite(sr, s5);
  srunner_add_suite(sr, s6);
  srunner_add_suite(sr, s7);
  srunner_add_suite(sr, s8);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
